image: ubuntu:18.04
before_script:
  - apt-get update -qq && apt-get install -y -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
deploy:
  type: deploy
  environment:
    name: live
    url: corinna-clack.de
  script:
    - ssh root@corinna-clack.de "cd /var/www/html/corinna-clack.de/ && git checkout master && git pull origin master && exit"
  only:
    - master
