image: ubuntu:18.04
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
deploy:
  type: deploy
  environment:
    name: live
    url: https://corinna-clack.de/
  script:
    - ssh root@corinna-clack.de "cd /var/www/html/deployment/ && git checkout master && git pull origin master && git log --oneline | head -n 5 && exit"
  only:
    - master
